### ISSUE TITLE
Unable to upload generated report as it has invalid contents

### ISSUE THREAD

**Issue by khonourhmrc** [tfsec/tfsec-sarif-action#3]
Have been using this action for sometime and just started hitting this issue when uploading sarif reports

The output error is:

```
Run tfsec sarif report
Unexpected token � in JSON at position 0
```

looks like the report generated is not valid

File being used is this:

```
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: tfsec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  
  schedule:
    - cron: '41 18 * * 1'

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Run tfsec
        uses: tfsec/tfsec-sarif-action@main
        with:
          sarif_file: tfsec.sarif         

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file:  tfsec.sarif  
```
